function newPath = apf_obstacle_avoidance(waypoints, obstacles)
    % APF-based obstacle avoidance
    % waypoints: generated by A* algorithm
    % obstacles: dynamic obstacles positions

    % Parameters for APF
    k_repulsive = 10;
    k_attractive = 1;
    repulsive_radius = 5;

    newPath = [];
    for i = 1:size(waypoints, 1)
        waypoint = waypoints(i, :);
        force = [0, 0];

        % Attractive force towards the waypoint
        force = force + k_attractive * (waypoint - currentPosition);

        % Repulsive force from obstacles
        for j = 1:size(obstacles, 1)
            obstacle = obstacles(j, :);
            distance = norm(currentPosition - obstacle);
            if distance < repulsive_radius
                force = force - k_repulsive * (1 / distance - 1 / repulsive_radius) * (currentPosition - obstacle) / distance^3;
            end
        end

        % Calculate the new position
        newPosition = currentPosition + force;
        newPath = [newPath; newPosition];
    end
end
